### ISSUE TITLE
Enable filter option doesn't seem to work

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#108]
### What is the current behaviour?

I have upgraded Contentment to v1.4.2 and I noticed "Enable filter" has been added. It seems this is enabled by default when creating new pickers.

![image](https://user-images.githubusercontent.com/2919859/116994432-ffd51480-acd8-11eb-880f-246374df30e6.png)

However I have some existing pickers where this in not enabled, but in both cases it seems to show the filter input above the item list in content section.

### What is the expected behaviour?

I would expect the option "Enable filter" to wither show or hide filter input. I tried re-saving the datatype instances, but it didn't seem to have any effect.

### Please tell us about your set-up:

- Contentment version: [1.4.2]
- Umbraco version: [8.13.0]
- Umbraco ModelsBuilder is: [enabled]
- Browser: [all]

**Comment by leekelleher** [comment]
@bjarnef Thanks for raising this.  I've fixed it in commit 9feaa943fbb370e7a6d1d338ff6057e5cbab4d39, but that's currently in the v2.0 branch. If there are other small fixes then I'll consider doing a v1.4.3 patch release, (it's been a busy past week with all the v9 beta movement, not had time to consider anything else). 🙄 

In the meantime, the workaround is to open the Item Picker options, toggle the "Enable filter" to whatever state you want, close the panel and save the DataType.

_Note:_ Re-saving the DataType without touching the "Enable filter" option will not save the value, _it's something to do with AngularJS not updating the model because the toggle's state had changed, I dunno._ 🤷
