### ISSUE TITLE
JSON DataList source to support a URL in addition to a file

### ISSUE THREAD

**Issue by hfloyd** [leekelleher/umbraco-contentment#110]
Hi Lee! Fantastic package 😊

### Is your feature request related to a problem? Please describe.
I was interested in providing a "Content Types" picker, but limiting the types to those which have templates, are not Elements, etc. I can easily write a webapi to return JSON in the perfect format for the JSON data source to consume, but if I provide a URL, nothing renders. If I save the output of my API as a file and put it into the config directory, then it renders as expected.

### Describe the solution you'd like

It would be awesome if the JSON could be provided by a dynamic source (webapi url)

### Describe alternatives you've considered

I suppose I could create some way to save the json as a file at various intervals, but that is extra overhead.

### Additional context
This works:
![image](https://user-images.githubusercontent.com/1252593/118908270-17beb200-b8ef-11eb-9cb8-762acb064d6a.png)

This doesn't work:
![image](https://user-images.githubusercontent.com/1252593/118907909-6455bd80-b8ee-11eb-89df-aaf41e794556.png)

**Comment by leekelleher** [comment]
Hi @hfloyd 👋 

The JSON data-source does support URLs (for API end-points) but the (my) assumption is that they'll start with either "http://" or "https://".  Otherwise it fall-back on the local filesystem.

This point has been brought up a few times recently, with a discussion about it here...
<https://github.com/leekelleher/umbraco-contentment/discussions/92>

I'm open to modifying the logic, but unsure which approach to take.  Feel free to reply on the discussion.

Alternatively, did you know that you can write your own custom data-sources?
<https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md#extending-with-your-own-custom-data-source>

**Comment by hfloyd** [comment]
Doh! 😮 Sorry, I didn't check the "Discussions" section... I will move my conversation over there... I didn't consider the custom datasource, which of course is another option... I will look into that as well.

**Comment by leekelleher** [comment]
No problem at all.  Makes me think that I need to update the Feature Request template to mention the Discussions section.

Also that the custom data-sources could be more discoverable.  All good things for me to consider. 👍

**Comment by hfloyd** [comment]
Would it be possible to add a documentation page specific to the CustomDataSource info, and possibly accept contributions of gists or something so people could share CustomDataSources? It would make it quick for people to get common ones into their project, and providing more examples will help people see how easy it is to create.

**Comment by leekelleher** [comment]
@hfloyd Great suggestion about having a custom data-source documentation page. I'll include it soon.

Just in case you didn't know, there are a bunch of hidden data-sources that have shipped since v1.4.0.
<https://github.com/leekelleher/umbraco-contentment/releases/tag/1.4.0> _(expand the 🤫 bits)_
The reason they are hidden is mostly because I didn't want to overwhelm newer users with a large selection of options.

I'm wondering whether an Umbraco Content Types data-source could be useful? with config options for showing Element Types (or not) and whether they have a Template, etc.  Just thinking out loud. 🤔 

---

I'll close off this ticket, as I think the original question is covered in the discussion on #92.
