### ISSUE TITLE
Data List - Item Picker overlay - item label doesn't wrap

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#119]
### What is the current behaviour?

When using a custom data source and a longer text it seems to overflow:

![image](https://user-images.githubusercontent.com/2919859/123267090-e85a2100-d4fc-11eb-84eb-7f7bbc4bb87c.png)

### What is the expected behaviour?

It would be great to wrap the text on next line to keep it inside the parent `<button>` element.

### Please tell us about your set-up:

- Contentment version: [1.4.4]
- Umbraco version: [8.13.1]
- Umbraco ModelsBuilder is: [enabled]
- Browser: [all]

**Comment by leekelleher** [comment]
@bjarnef Well spotted! 👀 

I've had a look at this to see what I can do. Turns out that it's Umbraco explicitly setting the CSS for the item to have `white-space: nowrap;`.

<https://github.com/umbraco/Umbraco-CMS/blob/release-8.13.1/src/Umbraco.Web.UI.Client/src/less/components/tree/umb-actions.less#L31>

I could fix this for Contentment, but really it's Umbraco setting the text to overflow.

If you need an immediate workaround, here's some custom CSS to add in...

```css
.contentment .umb-action-link {
    white-space: normal;
}
```

**Comment by bjarnef** [comment]
Yeah, it should probably be fixed in Umbraco.
Not sure if there's a specific reason `white-space: nowrap;` is set?

![image](https://user-images.githubusercontent.com/2919859/123381843-8992b700-d591-11eb-9000-4d03352fc57e.png)

**Comment by leekelleher** [comment]
I'm going to close this one off, as it's an Umbraco CSS issue.
In the meantime, a custom CSS workaround can be used.
