### ISSUE TITLE
Preview of Umbraco data

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#120]
### Is your feature request related to a problem? Please describe.

When using Umbraco Content as data source is seems it doesn't show preview of the data like a custom data source.

Would it be possible to show a preview of this? It would be okay to limit the results if there are many nodes, but nice to visualize the Xpath query works 😁 

![image](https://user-images.githubusercontent.com/2919859/123276008-18a5bd80-d505-11eb-8a05-89f12eb3ff27.png)

**Comment by leekelleher** [comment]
@bjarnef It will show a preview, but depends on the XPath expression used. If it's contextual, e.g. starts with one of the `$` parameters, then DataType has no context of that - as it's not in the Content tree.

For explicit/absolute XPath expressions, it will show the preview.

**Comment by bjarnef** [comment]
@leekelleher the XPath used is `$site//brandArchive` which has some Brand Page child nodes.

Some months ago a made this PR https://github.com/umbraco/Umbraco-CMS/pull/10049 to Umbraco as I noticed using XPath in MNTP didn't worked well in media and member section because it didn't know about the current site/root node, but if only a single root node exists it could be enhanced a bit 😎

**Comment by leekelleher** [comment]
My code is piggy-backing on Umbraco's [`UmbracoXPathPathSyntaxParser.ParseXPathQuery`](https://github.com/umbraco/Umbraco-CMS/blob/release-8.14.0/src/Umbraco.Core/Xml/UmbracoXPathPathSyntaxParser.cs#L91) method. So for the `$site` parameter, it there still needs to be a contextual Content node ID in order to traverse the tree.

Alternatively, if you do only have a single root node (e.g. level 1), then you could amend the XPath to use `$root/*[@level=1]`? or or because you're doing a descendants selector, go straight with `$root//brandArchive`? (though I prefer explicit naming, e.g. `$root/descendant::brandArchive[@isDoc]`).  That should give you a preview of the data-list items.

**Comment by bjarnef** [comment]
Okay thanks for the explanation @leekelleher
It works fine with `$site` variable in the XPath, so just more curios if there was a way to hack it in case only a single root node is available in content section 😁

So not that important and if there is no easy way to make that work, it is just the way it is! 😅

**Comment by leekelleher** [comment]
Yeah, I did look at various ways to make the preview work with contextual XPaths, but it became one of those things were I'd be adding more code to fulfil an edge-case, so I parked it.

I'll close off this ticket and add it to the Known Issues on the README. 👍
