### ISSUE TITLE
[v3.0] Umbraco 9 Smidge JavaScript errors with debug=false

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#185]
> _Originally posted by @bjarnef in https://github.com/leekelleher/umbraco-contentment/issues/176#issuecomment-965634352_

**Local environment**

![image](https://user-images.githubusercontent.com/2919859/141173857-c3bca487-2a70-4448-96d3-fa495a3d573e.png)

**Live environment**

![image](https://user-images.githubusercontent.com/2919859/141174002-f652b264-d9d8-4acd-837e-7c28683bf9f3.png)

It seems to happen because the assets for some reason isn't registered:

![image](https://user-images.githubusercontent.com/2919859/141176896-e52680d5-5d98-42e6-873e-513907409c8c.png)

---

I can see various controllers has `Umbraco.Community.Contentment.Services.DevMode` injected as `devModeService`, but I can't see where it is registered?
<https://github.com/leekelleher/umbraco-contentment/blob/dev/v3.x/src/Umbraco.Community.Contentment/DataEditors/DataList/data-list.editor.js#L11-L12>

Okay, it seems to be a hidden feature, which even GitHub search can't find 😅
here <https://github.com/leekelleher/umbraco-contentment/blob/develop/src/Umbraco.Community.Contentment/DataEditors/_/_dev-mode.js>

---

I think the missing registered services and controllers may be an issue with Smidge which are bundling the assets on Umbraco Cloud, but not locally. I have also noticed this started happening for my own controllers used the block custom views and this where the external login providers are missing: <https://github.com/umbraco/Umbraco.Cloud.Issues/issues/476#issuecomment-964857593>

**Comment by leekelleher** [comment]
Unfortunately, I haven't been able to reproduce this specific issue. I'll close the issue. Please feel free to re-open.

**Comment by bjarnef** [comment]
@leekelleher it may not be specific related to Contentment, but it seems if Smidge fails bundling some JS/CSS assets some later JS/CSS assets may not be registered as mentioned in https://github.com/bergmania/Bergmania.OpenStreetMap/issues/14

In the scenario my controllers for custom block views wasn't registered at all because of some bundle/minifying issues in OpenStreetMap v3.3.0 (which has a updated autocomplete.js asset) ... I reverted back to v3.2.0 and everything was working again.

Not sure in which order JS/CSS assets are registered - maybe in alphabetical order?

**Comment by biapar** [comment]
I've the same problem. How to solve?
