### ISSUE TITLE
Contentment breaks the Boot During Umbraco Installation

### ISSUE THREAD

**Issue by doronuziel71** [leekelleher/umbraco-contentment#34]
### What is the current behavior?

On a project where Contentnment is installed - remove the connection string and set the **Umbraco.Core.ConfigurationStatus**
to be empty - so to start a new installation. Boot Fails  - see screenshot.

### What is the expected behavior?

Umbraco Installation screen shows Up

### What is the motivation / use case for changing the behavior?
Use case - runnin the project in a new environment (For example - a new developer station with separate db), installing on a fresh DB, and then using USYNC to 'bootstrap' the DB.
### Please tell us about your set-up:

- Contentment version: [1.0.0]
- Umbraco version: [8.6.4]
- Browser _(if applicable?)_: all

### Anything else?

![image](https://user-images.githubusercontent.com/4950069/91029184-1df55b80-e607-11ea-96cf-945290e4a654.png)

**Comment by leekelleher** [comment]
Hi @doronuziel71, thanks for raising this. Just tried it out - yup, I can reproduce it _(bah, sucks!)_

I'll take a look at a fix later today.

**Comment by doronuziel71** [comment]
Hi @leekelleher  - Wow thanks for the quick response. 
I have created a PR - 
I have tested it in my environment and it seems to resolve the issue. 
I am not sure how much you will like it (It goes against the Anti-If statement movement). but I am issuing it just in case...

**Comment by leekelleher** [comment]
Thanks @doronuziel71. This is a good fix, I appreciate the pull request.

Due to how my version/branching structure is, (currently the 'develop' branch is for v1.1), so I'll retro-fit this for a v1.0.1 patch release. 👍 

I had a look around some other Umbraco packages, turns out that's how Shannon handles it for his Identity package. https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/Composing/UmbracoIdentityComposer.cs#L12

...and "Anti-If movement", first I'd heard it called that! 😅

**Comment by doronuziel71** [comment]
@leekelleher  - Thank you so much
