### ISSUE TITLE
SQL Data Source cannot be used on members

### ISSUE THREAD

**Issue by jonathoncove1** [leekelleher/umbraco-contentment#353]
### Which Contentment version are you using?

4.4.6

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

10.7.0

### Bug summary

When I try to use the Data List with an SQL Data source as a property editor on a member DocType, none of the properties of any member can be saved through the CMS. They can still be set in code through the IMemberService however. 

My Data List is targeting a custom database table and returning Name, Value & Description as per the instructions. Using the Data List with a manually specified data source does not produce the issue. 

The PostSave event does not throw any errors. 

### Steps to reproduce

Setup a clean install of Umbraco 10.7.0 
Add a custom database table with some values 
Create a Data List component with an SQL data source that targets the custom table
Create a new property against the member type that uses the new Data List component as the content editor (I used the item picker overlay)
Try to add a new member or save new data against an existing one 

### Expected result / actual result

Expected result is that the new data persists against a member. 
Actual result is that the data appears to stay in place, but disappears on a page refresh 

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by leekelleher** [comment]
@jonathoncove1 Thanks for reporting this.

I can definitely reproduce the bug. I've looked into the Data List code, but I can't figure out what is causing the Member to not persist the property value... it's very very weird.

As far as I can tell the SQL data-source isn't doing anything adverse that would prevent it from saving.

I've tried with several other data-sources, and they appear to work fine.  However when I do have multiple Data List editors on a Member node, then very very odd things start to happen, e.g. other values start to disappear, or with multiple selected values only the first value is returned.  It's all very odd.  I'm not exactly sure what the underlying problem is, nor how to go about fixing it. 😬 

I'll try investigate further, but fear that it's going to be a deep-dive stepping through Umbraco core source code. 😬

**Comment by leekelleher** [comment]
FYI, I've just tested this on Umbraco 8 (v8.17.0) with the latest Contentment (v4.5.0) and the Data List with SQL data-source saves perfectly fine. Nothing odd going on.  I'm thinking that something may have changed since the .NET port (Umbraco v9+), but I can't put my finger on it yet.

**Comment by leekelleher** [comment]
Update, I've stepped through the Umbraco source (latest `contrib` branch) - the bug is definitely still there. I've stepped through all the way down to saving the member data to the database, it all looks successful, but the SQL Data List value isn't persisted to the database, (in the `umbracoPropertyData` table).  I honestly have no idea why the SQL data-source doesn't work, but other data-sources - quite frustrating! 😖

**Comment by patrickdemooij9** [comment]
Kind of sounds like a scope isn't correctly completed. I'll see if I can take a look for you this weekend!

**Comment by leekelleher** [comment]
@patrickdemooij9 oooh yes, I think you're on to something - you've inspired me 🙏  I'll take another look this afternoon!
I'll let you know how I get on, otherwise might be something to collab on for [tomorrow's hackathon](https://www.meetup.com/umbraco-virtual/events/296099686/).

**Comment by leekelleher** [comment]
@jonathoncove1 Which type of database are you experiencing this with? SQL Server or SQLite? (or other? Azure?)

FYI, for my testing, I've been using SQLite (for v10 and v12) and SQLCE (for v8).

**Comment by patrickdemooij9** [comment]
Happy to see that you managed to get a potential fix 🙌 Hope it works for all the use cases

**Comment by leekelleher** [comment]
@patrickdemooij9 For my SQLite testing, adding `scope.Complete()` resolved the bug! e7b065782cac831eb523580c1ba29f94ba9ae692
Thank you for the pointer, it's very much appreciated. 🙏 _(I felt like I was going mad yesterday!)_

**Comment by leekelleher** [comment]
Thanks @jonathoncove1!
So far the fix is for SQLite, but hoping it'll be the same for SQL Server - I'll test this out next.

**Comment by leekelleher** [comment]
I haven't been able to reproduce the bug with SQL Server (on v10) - regardless of the SQLite fix in commit e7b065782cac831eb523580c1ba29f94ba9ae692.

With v11 and v12, I've realised that there is no code to support using an external custom database connection string, it would only work with the Umbraco database. _(Mostly because I have no idea how to handle generic SQL queries regardless of DB provider.)_ But that's a totally separate concern to this issue.

**Comment by jonathoncove1** [comment]
Brilliant, thanks! Will this appear in a package version soon?

**Comment by leekelleher** [comment]
@jonathoncove1 It'll most likely be another week or so, given that we're mid-Hacktoberfest, I can roll up any contributions in a patch release.
