### ISSUE TITLE
Alias name causes CSS issue

### ISSUE THREAD

**Issue by drpeck** [leekelleher/umbraco-contentment#407]
### Which Contentment version are you using?

5.0.1

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

13.4.0

### Bug summary

On a Block List the id attribute of the add button is set as per the alias name. This can cause unexpected issues with CSS inheritance from existing styles.
![image](https://github.com/leekelleher/umbraco-contentment/assets/1196047/de9c83a1-4293-4224-9b43-140b2d261351)

### Steps to reproduce

1. Create a Block list in a property called `navigation`
2. View the property in the content section. The add button will overlay the entire property editor because of an existing CSS style for `#navigation`

### Expected result / actual result

The button should appear below any added list items

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Edge

**Comment by leekelleher** [comment]
Argh, yes, this is definitely a problem, but I'm not sure I can do anything about it.

The reason for this is so that the property's label is wired up with the add button, e.g. click on the label it'll trigger the add button action (which in this case would open a model). Better in terms of accessibility, (making use of the `<label>`'s `for` attribute). The downside is that the `id` value should be unique in the DOM, so this runs the risk of an ID clash, (as you've seen with `navigation`). 😬 

Unless there's an alternative way to wire up a `<label>` with an input control, my suggestion would be rename the property alias, (not ideal, I know).
