### ISSUE TITLE
Data Picker: Single/string Member property saved/returned as a JSON array, not a string value

### ISSUE THREAD

**Issue by ewuski** [leekelleher/umbraco-contentment#424]
### Which Contentment version are you using?

5.0.0

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

13.2.1

### Bug summary

A `Member` property of the following data type:

Property Editor: `[Contentment] Data Picker`
Data Source: `Umbraco Languages`
Maximum items: `1`

in the model it is a string type:

```
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.2.1+383617e")]
[global::System.Diagnostics.CodeAnalysis.MaybeNull]
[ImplementPropertyType("uiLanguage")]
public virtual string UiLanguage => this.Value<string>(_publishedValueFallback, "uiLanguage");
```

When querying with

`var currentUiLang = member.GetValue<string>(uiLanguageAlias);`

it returns a JSON array instead of a single string value:

`["pt-BR"]`

Is this correct?

### Steps to reproduce

The property setup:

<img width="518" alt="Task-2887(1)" src="https://github.com/user-attachments/assets/a7a7e48d-52ee-49c8-b552-d11918eb3230">

The result:

<img width="907" alt="Task-2887(2)" src="https://github.com/user-attachments/assets/0dd46a3a-dce9-4bde-87a9-949176864345">

### Expected result / actual result

I would expect if the model property is a `string`, the value should be saved as a string in the database and be returned as a `string` value, not a JSON string.

The same type in a content model property is returned as a string, not a JSON string.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by leekelleher** [comment]
@ewuski Thanks for raising this.

I suspect that in your code example, the `member` is an `IMember` type, not the `IPublishedContent` version of the member data? The difference between these is that the `IMember` deals with the values as they are stored in the database, whereas the `IPublishedContent` (of a member) the values are processed through the value-converters.

In terms of the Data Picker value-converter, it wont run against the `IMember` object, but it will run against the `IPublishedContent` (which uses the ModelsBuilder generated classes).

 It's been a while since I've worked with member data on a website, from what I recall, you should be able to pass in the `IMember` object to `UmbracoContext.PublishedSnapshot.Members.Get(member)` to get the `IPublishedContent` version back.

I'll close off this ticket, as it's not a bug with Data Picker or the Contentment package specifically.
