### ISSUE TITLE
Content Blocks strange behavior on copy element

### ISSUE THREAD

**Issue by gcutroneo** [leekelleher/umbraco-contentment#432]
### Which Contentment version are you using?

v5.0.2

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

13.5.2

### Bug summary

On a page I have a property of type content blocks.
The possible elements for content blocks are all of type “element”.
When the elements themselves have a “content blocks” property, the “Copy” function works randomly, and does not hold more than an element or two in memory, and not in the time order of selection. 
The problem is definitely from the multiple levels of “Content blocks”, I wanted to know if it has ever been encountered by others.

### Steps to reproduce

Create an “element” A in Umbraco with a single property of type “textstring”.
Create a Content Blocks X data type that uses A.
Create an “element” B in Umbraco with a property of type X.
Create a Content Blocks data type Y that uses B.
Create a page C in Umbraco with a property of type Y.
Create a few blocks in Y, try to perform COPY on more than one block.

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by leekelleher** [comment]
@gcutroneo Thanks for reporting this.

From revisiting the code, (_it's been 4 years since I'd touched it_, 944586c7610434e7d10bdf54fdf821d495fab2f4), it looks that the feature was developed to only copy a single element (block) per element-type.  I'm not entirely sure why that decision was made back then, it could have been a limitation of the `clipboardService` (in Umbraco), or it could have been an oversight. 😕  

I'll investigate to see if it's possible to resolve this and copy multiple elements (blocks).

**Comment by leekelleher** [comment]
I have a fix ready for this, #438. It'll be part of the next release (soon).
