### ISSUE TITLE
Adjustment of icon picker

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#54]
### Describe the solution you'd like

I noticed in Icon Picker it has the following markup.
https://github.com/leekelleher/umbraco-contentment/blob/master/src/Umbraco.Community.Contentment/DataEditors/IconPicker/icon-picker.html#L16-L21

You might want to replace this with `<umb-file-icon>` component instead unless you are supporting older Umbraco v8 versions:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/umbfileicon.directive.js

It could be replaced with the following:

```
<umb-file-icon
      icon="{{model.value}}"
      text="{{vm.label}}"
      size="s">
</umb-file-icon>
```

**Comment by leekelleher** [comment]
Thanks @bjarnef 👍
I'm currently building against v8.6.1 - I'll take a look see what version `<umb-file-icon>` was introduced in!

**Comment by bjarnef** [comment]
@leekelleher it was introduced in v8.4.0 😁
https://github.com/umbraco/Umbraco-CMS/pull/6293

**Comment by leekelleher** [comment]
I tried it out, but turns out there is a subtle difference in what I'm doing in Contentment's Icon Picker.

For the label/text, I'm outputting HTML...
<https://github.com/leekelleher/umbraco-contentment/blob/1.0.1/src/Umbraco.Community.Contentment/DataEditors/IconPicker/icon-picker.html#L20>

... I put a `<br>` between the icon name and colour, so to balance it - I didn't like the text-wrapping on longer labels...
<https://github.com/leekelleher/umbraco-contentment/blob/1.0.1/src/Umbraco.Community.Contentment/DataEditors/IconPicker/icon-picker.js#L21>

The `<umb-file-icon>`s `text` property doesn't render the markup.
<https://github.com/umbraco/Umbraco-CMS/blob/release-8.4.0/src/Umbraco.Web.UI.Client/src/views/components/umb-file-icon.html#L6>

Thanks again for the suggestion. 👍  I do like trying to re-use as much as I can from Umbraco directives/components.

**Comment by bjarnef** [comment]
@leekelleher yeah, at the time as was adding the component there wasn't a need to break lines and wrapping word via CSS would be fine.

It could eventually use `ng-include` if there is a specific need, where it would be possible to replace icon and text.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html#L34

or if could allow render HTML like `<br>`.

In this case I am not sure why it always need replace space with `<br>`?
https://github.com/leekelleher/umbraco-contentment/blob/1.0.1/src/Umbraco.Community.Contentment/DataEditors/IconPicker/icon-picker.js#L21

If the value if from a `<textarea>` it could replace newline with `<br>`, which would still allow spaces in label.
Something like this: https://stackoverflow.com/a/784547

```
str = str.replace(/(?:\r\n|\r|\n)/g, '<br>');
```

**Comment by leekelleher** [comment]
> In this case I am not sure why it always need replace space with `<br>`?

@bjarnef For my Icon Picker, replacing the space with a `<br>` is because the selected icon's name and colour are separated by a space. If I don't line-break them, it'll often look unbalanced (to me). Edge-case I guess.

I keep `<umb-file-icon>` in mind for future use. 👍

**Comment by bjarnef** [comment]
@leekelleher okay, I would probably just split the icon name and color classes and use only the icon name as text and the color class in the styling, e.g. something like this:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.controller.js#L62-L63

https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/icon-picker.md
