### ISSUE TITLE
Allow empty option dropdownlist multiple blank options

### ISSUE THREAD

**Issue by Matthew-Wise** [leekelleher/umbraco-contentment#61]
### What is the current behaviour?

I have a drop down list with allow empty using an Enum data source (I don't believe data source type matters). If you save the content with altering the property, on refresh you will see two blank options.

![image](https://user-images.githubusercontent.com/6782865/102776586-e44f1a00-4386-11eb-861f-08cd704d1504.png)

example is using DTGE.

### What is the expected behaviour?

There should only be one blank option.

- Contentment version: [1.1.1]
- Umbraco version: [8.9.1]
- Browser _(if applicable?)_: not applicable (but tested in chrome)

**Comment by leekelleher** [comment]
I recall looking into this when I first made it, there was some quirk with how AngularJS adds in the empty `<option>`. At the time I couldn't figure out a resolution, so left it.

Thinking about it now, it could be a resolution to **not** display the (intentional) empty `<option>` if `$scope.model.value` is empty. Meaning that AngularJS would still do its optional thing. 🤔 
<https://github.com/leekelleher/umbraco-contentment/blob/1.1.1/src/Umbraco.Community.Contentment/DataEditors/DropdownList/dropdown-list.html#L12>

**Comment by leekelleher** [comment]
Good news, I have a fix for this.
But I haven't decided whether this should be part of upcoming v1.2.0, or do it as a v1.1.x patch release. 🤔

**Comment by leekelleher** [comment]
This has been fixed in v1.1.2 patch release - out now!
