### ISSUE TITLE
Data List editor get Umbraco Content below multiple matching nodes

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#78]
I wonder if it is possible using Data List and list nodes under multiple parent nodes? Currently it seems to Xpath option only list children of first matching node.

**Example**

I have the following content structure and some "subjects" under these two nodes:

![image](https://user-images.githubusercontent.com/2919859/110708077-7cc4a000-81fa-11eb-800a-d6e9a0215dad.png)

However e.g. when render the data as a checkbox list it only shows the elements below first matching node:

![image](https://user-images.githubusercontent.com/2919859/110708202-9cf45f00-81fa-11eb-8293-46c089b88b97.png)

It is possible to configurate MNTP to a parent node and only allow specific child nodes.

For this specific use-case it should be useful to show e.g. "Privat" (Private) and "Erhvev" (Business) and list the checkboxes below. Some of the subjects/topics could have same names under the two groups.

![image](https://user-images.githubusercontent.com/2919859/110709461-7fc09000-81fc-11eb-8524-1f97709400d5.png)

It is a bit related to this having optgroup in dropdownlist: https://github.com/leekelleher/umbraco-contentment/issues/51

**Comment by leekelleher** [comment]
Hi @bjarnef, thanks for the question/suggestion.

> I wonder if it is possible using Data List and list nodes under multiple parent nodes?

The "Umbraco Content" data source (that part of Contentment), only supports a single parent node.

> Currently it seems to XPath option only list children of first matching node

That's correct. That's how it was designed, (for my own client use-cases).

My original prototypes for Umbraco Content did go quite experimental, with more XPath options, etc. But development halted by too many options, too many edge-cases, it got complicated. So it was ship something rather than nothing.

Also, I get the sense that XPath support in Umbraco is something that will eventually be phased out... so I didn't want to invest too much effort into designing, developing and supporting something that wasn't useful.  Personally I can't think of another way text-based DSL to query hierarchal data structures better than how XPath does it. _C'est la vie._

You could try creating a custom data source? [(Documentation here)](https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md#extending-with-your-own-custom-data-source)

---

re: #51 I still like the idea of Groups, I'd started a prototype, but still requires a significant development effort to complete.

**Comment by bjarnef** [comment]
@leekelleher yes, it will probably be too complex and not needed in most use-cases.
I think for this use-case I will either use MNTP or split the Data List into two data types and thus two properties to select items under each parent.

**Comment by leekelleher** [comment]
Closing this ticket off. I've added a hidden feature 🤫 to upcoming v1.4, to have an advanced XPath for querying Umbraco Content, ref: commit 2f94022badf075990a72a93316ecebee966f3e2b.

_re: hidden features, I've developed many custom data-sources, but feel that a long list of data-sources would be quite overwhelming for a non-advanced user, so have made them to be "unlockable" features. I'll explain more closer to the time of v1.4 release._

Data List Groups is still relevant, and covered by ticket #51. 👍
