### ISSUE TITLE
Add readonly/label editor

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#98]
### Is your feature request related to a problem? Please describe.

Sometimes you want to store reference to external data in a property editor, e.g. using Label in core and properties "External Id" and "External Name". You could also store the raw JSON in Label (string), but doesn't look nice.

### Describe the solution you'd like

It could be useful to store an entity/object as JSON in a readonly/label editor and maybe a custom view/template to present to data, e.g.

```
Id: 1234
Name Unicorn
Category: Creatures
```

**Comment by leekelleher** [comment]
As a property-editor? 

Contentment does have a couple of read-only "editors" - ["readonly-node-preview.html"](https://github.com/leekelleher/umbraco-contentment/tree/develop/src/Umbraco.Community.Contentment/DataEditors/ReadOnly) is used on Content Blocks to show the selected ElementType.  [Notes](https://github.com/leekelleher/umbraco-contentment/tree/develop/src/Umbraco.Community.Contentment/DataEditors/Notes) is potentially reusable? or maybe [Render Macro](https://github.com/leekelleher/umbraco-contentment/tree/develop/src/Umbraco.Community.Contentment/DataEditors/RenderMacro)?

I did prototype a read-only editor using `<umb-code-snippet>` directive, but was one of those where I had no _real world_ use for it. 🤷

**Comment by bjarnef** [comment]
Yes, exactly 👌
I could be useful with some simple HTML formatting, e.g.

```
Name: <strong>{{model.name}}</strong><br>
Id: {{model.id}}
```

**Comment by leekelleher** [comment]
Okay, so a "Templated Label"?

Actually, [Notes](https://github.com/leekelleher/umbraco-contentment/tree/develop/src/Umbraco.Community.Contentment/DataEditors/Notes) isn't too far away from this, as the view can render AngularJS templates/directives.  The only limitation is that the DataType field uses TinyMCE, say instead of ACE. Hmmm, getting me thinking. 🤔

**Comment by leekelleher** [comment]
@bjarnef I've did a quick prototype.

![Screenshot 2021-04-20 174955](https://user-images.githubusercontent.com/209066/115434650-d7411b00-a200-11eb-84db-6f09ee4bbd23.png)

Swapped out one of my properties that had some Content Blocks data in there.

![Screenshot 2021-04-20 175037](https://user-images.githubusercontent.com/209066/115434797-02c40580-a201-11eb-95ff-ad7707acc6fc.png)

Turns out that I was able to reuse my Notes editor-view.  I only had to use 3 classes... and one of those is the ValueConverter, which is only there for playing nice with ModelsBuilder support.  I've put them in a Gist, if you wanted to play with it?

<https://gist.github.com/leekelleher/cfa4f3585ea0616241f22b3508f06e99>

I'm not 100% sold on the idea of included this as default with Contentment yet. It's one of those where I'd want to play with it more, incubate the idea, etc. _(I'm funny that way)_ 😆
